name: Savannah Orders

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test with pytest
      run: |
        poetry run test

    - name: Check code style with black
      run: |
        poetry run black --check src tests

    - name: Run mypy for type checking
      run: |
        poetry run mypy src

    - name: Run security checks with bandit
      run: |
        poetry run bandit -r src -c pyproject.toml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml 
        fail_ci_if_error: true